repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-byte-order-marker
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check backend --config ./pyproject.toml
        args: [--fix]
        language: system
        types: [python]
        exclude: ^(.ci/|.apt/|setup.py)
      - id: ruff-format
        name: ruff-format
        entry: ruff format backend --config ./pyproject.toml
        language: system
        types: [python]
        exclude: ^(.ci/|.apt/)
  - repo: https://github.com/opensource-nepal/commitlint
    rev: v1
    hooks:
      - id: commitlint
