services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/maeuschen/backend
    command: python app.py
    network_mode: host
    volumes:
      - ./backend:/home/maeuschen/backend
      - ./frontend:/home/maeuschen/frontend
