services:
  dev:
    image: public_transport_airbnb
    command: python backend/app.py
    network_mode: host
    volumes:
      - ./backend:/home/maeuschen/backend
      - ./frontend:/home/maeuschen/frontend
    ports:
      - "8989:8989"
