services:
  backend:
    build: ./backend
    working_dir: /home/maeuschen/backend
    network_mode: host
    volumes:
      - ./backend:/home/maeuschen/backend
    command: flask --app app.py --debug run
  frontend:
    build: ./react-frontend
    working_dir: /home/maeuschen/frontend
    network_mode: host
    volumes:
      - ./react-frontend:/home/maeuschen/frontend
      - /home/maeuschen/frontend/node_modules
    command: npm start 

