on:
  push:
    branches: [ '**' ]  # Runs on every branch
  pull_request:
    branches: [ '**' ]  # Runs on every branch

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: ./frontend
        run: |
          docker build -t ${{ github.event.repository.name }}_frontend .

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: ./backend
        run: |
          docker build -t ${{ github.event.repository.name }}_backend .
